plugin: aws_ec2
aws_access_key: AKIAQ4UK7J35ECH4POB7
aws_secret_key: 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
regions:
  - us-east-1

hostnames:
  - ip-address

#keyed_groups:
#  - prefix: OS_run
#    key: platform_details
###    key: placement.region 

groups:
  linux: "'linux' in tags.Name"
  windows: "'windows' in tags.Name"
