---
- name: Run a command and print output
  hosts: all
  gather_facts: true

  tasks:

    - name: Run the command
      command: "/opt/nessus_agent/sbin/nessuscli agent status"
      register: scan_info
      ignore_errors: true

    - name: Generate HTML Table
      set_fact:
        html_table: |
          <html>
          <head>
            <style>
              table {
                font-family: Arial, sans-serif;
                border-collapse: collapse;
                width: 100%;
              }
              th, td {
                border: 1px solid #dddddd;
                text-align: left;
                padding: 8px;
              }
              th {
                background-color: #f2f2f2;
              }
            </style>
          </head>
          <body>
            <h2>Scan Information</h2>
            <table>
              <tr>
                <th>Hostname</th>
                {% for line in scan_info.stdout_lines %}
                  {% if line | regex_search('^(.*?):(.*)$') %}
                    {% set key, value = line.split(':') %}
                    <th>{{ key | trim }}</th>
                  {% endif %}
                {% endfor %}
              </tr>
              <tr>
                <td>{{ inventory_hostname }}</td>
                {% for line in scan_info.stdout_lines %}
                  {% if line | regex_search('^(.*?):(.*)$') %}
                    {% set key, value = line.split(':') %}
                    <td>{{ value | trim }}</td>
                  {% endif %}
                {% endfor %}
              </tr>
            </table>
          </body>
          </html>
      delegate_to: localhost

    - name: Save HTML Table to File
      copy:
        content: "{{ html_table }}"
        dest: "/etc/ansible/html_output_all_hosts.html"
      delegate_to: localhost
      run_once: true

